  name: CI/CD
  on:
    push:
      branches:
        - main
  jobs:
    build:
      name: Build & deploy
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Install Node
          uses: actions/setup-node@v2
          with:
            node-version: 16
        - name: Install packages
          run: npm i
        - name: Install Angular
          run: npm install -g @angular/cli > /dev/null
        - name: Build
          run:  ng build --base-href="https://elhombresinnombre.github.io/angular-material-graphql/"
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.2.5
          with:
            branch: gh-pages
            folder: dist/angular-material
            token: ${{ secrets.GITHUB_TOKEN }}
